{pkgs}: {
  deps = [
    pkgs.timidity
    pkgs.python310Packages.pwntools
    pkgs.sox
    pkgs.mullvad
    pkgs.run
    pkgs.python310Packages.clvm-tools
    pkgs.haskellPackages.synthesizer-midi
    pkgs.midori-unwrapped
    pkgs.haskellPackages.alsa-midi
    pkgs.haskellPackages.PortMidi
    pkgs.haskellPackages.essence-of-live-coding-PortMidi
    pkgs.haskellPackages.RtMidi
    pkgs.haskellPackages.midair
    pkgs.haskellPackages.mime-directory
    pkgs.open-music-kontrollers.midi_matrix
    pkgs.midi-trigger
    pkgs.MIDIVisualizer
    pkgs.haskellPackages.midi-alsa
    pkgs.haskellPackages.midi
    pkgs.sbclPackages.midi
    pkgs.midimonster
    pkgs.haskellPackages.midisurface
    pkgs.emacsPackages.midi-kbd
    pkgs.midicsv
    pkgs.python311Packages.midiutil
    pkgs.python310Packages.midiutil
    pkgs.haskellPackages.midimory
    pkgs.haskellPackages.midi-utils
    pkgs.haskellPackages.midi-music-box
    pkgs.perlPackages.MailPOP3Client
    pkgs.perl536Packages.MailPOP3Client
    pkgs.perl538Packages.MailPOP3Client
    pkgs.sbclPackages.mpg123-ffi
    pkgs.mpc123
    pkgs.mpg123
    pkgs.haskellPackages.mpg123-bindings
    pkgs.sbclPackages.mixalot-mp3
    pkgs.mpg321
    pkgs.haskellPackages.mp3decoder
    pkgs.perlPackages.MP3Info
    pkgs.perl538Packages.MP3Info
    pkgs.perl538Packages.MP3Tag
    pkgs.mp3val
    pkgs.perlPackages.MP3Tag
    pkgs.mp3gain
    pkgs.mp3fs
    pkgs.perlPackages.MP3CutGapless
    pkgs.mp3splt
    pkgs.mp3info
    pkgs.perl536Packages.MP3Info
    pkgs.mp3blaster
    pkgs.perl538Packages.MP3CutGapless
    pkgs.sbclPackages.mp3-duration-test
    pkgs.perl536Packages.MP3Tag
    pkgs.haskellPackages.musicxml2
    pkgs.haskellPackages.music-dynamics-literal
    pkgs.haskellPackages.music-preludes
    pkgs.music-player
    pkgs.haskellPackages.musicScroll
    pkgs.haskellPackages.music-dynamics
    pkgs.haskellPackages.musicw
    pkgs.haskellPackages.musicbrainz-email
    pkgs.haskellPackages.musicxml
    pkgs.python310Packages.musicbrainzngs
    pkgs.python310Packages.music-tag
    pkgs.haskellPackages.sound-collage
    pkgs.python310Packages.soundfile
    pkgs.sound-of-sorting
    pkgs.soundtouch
    pkgs.soundOfSorting
    pkgs.emacsPackages.soundklaus
    pkgs.python310Packages.soundcloud-v2
    pkgs.soundtracker
    pkgs.sound-theme-freedesktop
    pkgs.soundfont-arachno
    pkgs.python311Packages.soundcloud-v2
    pkgs.ocamlPackages.soundtouch
    pkgs.python311Packages.soundfile
    pkgs.haskellPackages.sounddelay
    pkgs.libsForQt5.soundkonverter
    pkgs.soundkonverter
    pkgs.dwarf-fortress-packages.soundSense
    pkgs.haskellPackages.sound-change
    pkgs.emacsPackages.soundcloud
    pkgs.soundconverter
    pkgs.plasma5Packages.soundkonverter
    pkgs.haskellPackages.soundgen
    pkgs.python310Packages.sounddevice
    pkgs.python311Packages.pysoundfile
    pkgs.soundwireserver
    pkgs.python310Packages.pysoundfile
    pkgs.python311Packages.sounddevice
    pkgs.rPackages.karel
    pkgs.rPackages.dfmta
    pkgs.perlPackages.CPAN02PackagesSearch
    pkgs.rPackages.pcLasso
    pkgs.llvmPackages_6.libllvm
    pkgs.gcr
    pkgs.nwg-drawer
    pkgs.libsForQt5.plasma-sdk
    pkgs.home-assistant-component-tests.lyric
    pkgs.quicklispPackages.cl-who
    pkgs.haskellPackages.IndexedList
    pkgs.rubyPackages.solargraph
    pkgs.rubyPackages_2_7.mini_magick
    pkgs.rubyPackages_3_3.rbnacl
    pkgs.urbanterror
    pkgs.vimPlugins.vim-be-good
    pkgs.poco
    pkgs.xorg.xf86videorendition
    pkgs.haskellPackages.mcl
    pkgs.emacsPackages.elfeed-goodies
    pkgs.rPackages.AhoCorasickTrie
    pkgs.haskellPackages.linklater
    pkgs.rPackages.HPiP
    pkgs.perl536Packages.ImageSane
    pkgs.clickclack
    pkgs.lispPackages.css-selectors
    pkgs.python311Packages.webssh
    pkgs.php83Extensions.zend_test
    pkgs.patchelfUnstable
    pkgs.fsharp
    pkgs.python311Packages.gtts
    pkgs.ffmpeg-full
    pkgs.firebase-tools
    pkgs.codimd
    pkgs.python311Packages.django_5
    pkgs.python311Packages.clvm-tools
    pkgs.dig
    pkgs.incus
    pkgs.q
  ];
}
